name = "Jobstone Necklace Auto-Switcher"
author = "Laele"
punchline = "Auto-selects the Jobstones Necklaces pendant for your current job."
description = """
Detects job/soul crystal changes and toggles the Jobstones Necklaces Penumbra mod option accordingly.
Requires the Jobstones Necklaces mod and Penumbra.
"""
repo_url = "https://github.com/laele-hali/JobstoneNecklaceSwitcher"
tags = ["penumbra", "necklace", "jobstone", "dalamud"]
internal_name = "JobstoneNecklaceSwitcher"
assembly_version = "0.1.0"
dalamud_api_level = 13
load_priority = 0
